version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/web-build
    overwrite: yes
permissions:
  - object: /home/ec2-user/deploy/web-build
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 1000
      runas: ec2-user
